description: Huskie Hackers is a competitive and social club that involves hackathons and coming together to discuss computer science. 

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

